name: Test

on:
  push:
    branches:
      - main

jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: denoland/setup-deno@v1.1.0
        with:
          deno-version: v1.14.3
      - run: ./scripts/test.sh
